// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {ElectionRegistry} from "../src/ElectionRegistry.sol";
import {BallotBox} from "../src/BallotBox.sol";
import {SemaphoreVerifier} from "@semaphore-protocol/contracts/base/SemaphoreVerifier.sol";

/**
 * End-to-end test: real proofs, real verifier, real registry.
 *
 * The proofs in `fixtures/vote-proofs.json` were generated by
 * `packages/circuits/scripts/generate-contract-fixtures.mjs` on Semaphore's audited circuit with
 * the pinned 4.13.0 trusted-setup artifacts — not fabricated. Loading them here means this suite
 * proves the whole chain: a proof TypeScript generated is accepted by the audited Solidity
 * verifier, through BallotBox, against a scope the contract derives in Solidity from an election
 * id. If the TypeScript and Solidity scope derivations ever drift, every test below fails.
 *
 * Regenerate with:
 *   cd packages/circuits && pnpm build && node scripts/generate-contract-fixtures.mjs
 */
contract BallotBoxTest is Test {
    // --- fixture values (vote-proofs.json) -----------------------------------------

    // All proof values are read from `fixtures/vote-proofs.json` rather than transcribed, so a
    // regenerated fixture cannot drift from what the tests assert.

    // --- state ----------------------------------------------------------------------

    SemaphoreVerifier internal verifier;
    ElectionRegistry internal registry;
    BallotBox internal ballotBox;

    address internal admin = makeAddr("admin");
    address internal voter = makeAddr("voter");

    string internal fixtureJson;

    /// Fixture election ids, loaded from the JSON as decimal strings.
    bytes32 internal electionA;
    bytes32 internal electionB;

    uint64 internal constant NOW = 1_900_000_000;
    uint64 internal constant ELIGIBILITY_CLOSE = 2_000_000_000;
    uint64 internal constant VOTING_CLOSE = 2_100_000_000;

    function setUp() public {
        vm.warp(NOW);
        fixtureJson = vm.readFile("test/fixtures/vote-proofs.json");

        verifier = new SemaphoreVerifier();
        registry = new ElectionRegistry(address(verifier), admin);
        ballotBox = new BallotBox(registry);

        // The on-chain election id is the integer the scope was derived from, as bytes32.
        electionA = bytes32(vm.parseUint(vm.parseJsonString(fixtureJson, ".electionIdA")));
        electionB = bytes32(vm.parseUint(vm.parseJsonString(fixtureJson, ".electionIdB")));

        // Elections are created against the root the proofs were built with.
        uint256 root = vm.parseJsonUint(fixtureJson, ".merkleTreeRoot");
        vm.prank(admin);
        registry.createElection(electionA, bytes32(root), 3, ELIGIBILITY_CLOSE, VOTING_CLOSE, [uint256(1), uint256(2)]);
        vm.prank(admin);
        registry.createElection(electionB, bytes32(root), 3, ELIGIBILITY_CLOSE, VOTING_CLOSE, [uint256(1), uint256(2)]);
    }

    // --- fixture readers -------------------------------------------------------------

    function _points(string memory key) internal view returns (uint256[8] memory points) {
        uint256[] memory flat = vm.parseJsonUintArray(fixtureJson, string.concat(".", key, ".points"));
        for (uint256 i = 0; i < 8; i++) {
            points[i] = flat[i];
        }
    }

    function _proof(string memory key) internal view returns (BallotBox.SemaphoreProof memory) {
        return BallotBox.SemaphoreProof({
            merkleTreeRoot: vm.parseJsonUint(fixtureJson, string.concat(".", key, ".merkleTreeRoot")),
            nullifier: vm.parseJsonUint(fixtureJson, string.concat(".", key, ".nullifier")),
            message: vm.parseJsonUint(fixtureJson, string.concat(".", key, ".message")),
            scope: vm.parseJsonUint(fixtureJson, string.concat(".", key, ".scope")),
            points: _points(key),
            merkleTreeDepth: vm.parseJsonUint(fixtureJson, string.concat(".", key, ".merkleTreeDepth"))
        });
    }

    function _ciphertext(string memory key) internal view returns (uint256[4] memory ct) {
        uint256[] memory flat = vm.parseJsonUintArray(fixtureJson, string.concat(".", key));
        for (uint256 i = 0; i < 4; i++) {
            ct[i] = flat[i];
        }
    }

    function _cpProof(string memory key) internal view returns (bytes memory) {
        return vm.parseBytes(vm.parseJsonString(fixtureJson, string.concat(".", key)));
    }

    // --- tests -----------------------------------------------------------------------

    function _cast(bytes32 electionId, string memory ctKey, string memory cpKey, string memory proofKey) internal {
        ballotBox.castVote(electionId, _ciphertext(ctKey), _cpProof(cpKey), _proof(proofKey));
    }

    /// A proof this repository generated on the real circuit is accepted on-chain.
    function test_CastVote_AcceptsRealCircuitProof() public {
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofA1");
        assertTrue(ballotBox.isNullifierUsed(electionA, _proof("proofA1").nullifier));
    }

    /// The Solidity scope derivation must equal the TypeScript one, or nothing verifies.
    function test_ElectionScope_MatchesOffChainDerivation() public view {
        assertEq(ballotBox.electionScope(electionA), vm.parseJsonUint(fixtureJson, ".scopeA"));
        assertEq(ballotBox.electionScope(electionB), vm.parseJsonUint(fixtureJson, ".scopeB"));
    }

    /// Swapping the ciphertext under a valid proof must fail: the commitment is recomputed.
    function test_CastVote_RevertsOnSwappedBallotCommitment() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");

        vm.expectRevert(
            abi.encodeWithSelector(
                BallotBox.BallotCommitmentMismatch.selector,
                vm.parseJsonUint(fixtureJson, ".commitment2"),
                proof.message
            )
        );
        _cast(electionA, "ciphertext2", "chaumPedersenProof2", "proofA1");
    }

    /// A valid proof for election B must not count as a ballot in election A.
    function test_CastVote_RevertsWhenProofIsForAnotherElection() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofB1");

        vm.expectRevert(
            abi.encodeWithSelector(
                BallotBox.ScopeMismatch.selector, electionA, ballotBox.electionScope(electionA), proof.scope
            )
        );
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofB1");
    }

    /// Two ballots from one voter in one election share a nullifier — the second must revert.
    /// This is the double-vote property the circuits work promised.
    function test_CastVote_RejectsSecondVoteInSameElection() public {
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofA1");

        BallotBox.SemaphoreProof memory proofA1 = _proof("proofA1");
        BallotBox.SemaphoreProof memory proofA2 = _proof("proofA2");
        // The premise the test depends on: a changed ballot still spends the same nullifier.
        assertEq(proofA2.nullifier, proofA1.nullifier);

        vm.expectRevert(abi.encodeWithSelector(BallotBox.NullifierAlreadyUsed.selector, electionA, proofA1.nullifier));
        _cast(electionA, "ciphertext2", "chaumPedersenProof2", "proofA2");
    }

    /// The same ballot in a different election is a different vote, and must be accepted.
    function test_CastVote_AcceptsSameBallotInDifferentElection() public {
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofA1");
        _cast(electionB, "ciphertext1", "chaumPedersenProof1", "proofB1");

        assertNotEq(_proof("proofA1").nullifier, _proof("proofB1").nullifier);
        assertTrue(ballotBox.isNullifierUsed(electionA, _proof("proofA1").nullifier));
        assertTrue(ballotBox.isNullifierUsed(electionB, _proof("proofB1").nullifier));
    }

    /// Nullifiers are not shared between elections, so a spent one elsewhere does not block here.
    function test_IsNullifierUsed_IsFalseBeforeVoting() public view {
        assertFalse(ballotBox.isNullifierUsed(electionA, _proof("proofA1").nullifier));
    }

    function test_CastVote_EmitsVoteCast() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");

        vm.expectEmit(true, true, true, true, address(ballotBox));
        emit BallotBox.VoteCast(
            electionA, proof.nullifier, proof.message, _ciphertext("ciphertext1"), _cpProof("chaumPedersenProof1")
        );
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofA1");
    }

    function test_CastVote_RevertsAfterVotingClose() public {
        vm.warp(VOTING_CLOSE);
        vm.expectRevert(abi.encodeWithSelector(BallotBox.VotingClosed.selector, electionA, uint64(VOTING_CLOSE)));
        _cast(electionA, "ciphertext1", "chaumPedersenProof1", "proofA1");
    }

    /// Voting in an election the registry has never heard of is the registry's error, not ours.
    function test_CastVote_RevertsOnUnknownElection() public {
        bytes32 unknown = keccak256("never-created");
        vm.expectRevert(abi.encodeWithSelector(ElectionRegistry.ElectionNotFound.selector, unknown));
        _cast(unknown, "ciphertext1", "chaumPedersenProof1", "proofA1");
    }

    function test_CastVote_RevertsOnTamperedMerkleRoot() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");
        proof.merkleTreeRoot = proof.merkleTreeRoot + 1;

        vm.expectRevert(
            abi.encodeWithSelector(
                BallotBox.MerkleRootMismatch.selector,
                bytes32(vm.parseJsonUint(fixtureJson, ".merkleTreeRoot")),
                proof.merkleTreeRoot
            )
        );
        ballotBox.castVote(electionA, _ciphertext("ciphertext1"), _cpProof("chaumPedersenProof1"), proof);
    }

    function test_CastVote_RevertsOnUnsupportedDepth_Below() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");
        proof.merkleTreeDepth = 0;
        vm.expectRevert(abi.encodeWithSelector(BallotBox.MerkleTreeDepthUnsupported.selector, 0, 1, 32));
        ballotBox.castVote(electionA, _ciphertext("ciphertext1"), _cpProof("chaumPedersenProof1"), proof);
    }

    function test_CastVote_RevertsOnUnsupportedDepth_Above() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");
        proof.merkleTreeDepth = 33;
        vm.expectRevert(abi.encodeWithSelector(BallotBox.MerkleTreeDepthUnsupported.selector, 33, 1, 32));
        ballotBox.castVote(electionA, _ciphertext("ciphertext1"), _cpProof("chaumPedersenProof1"), proof);
    }

    /// A tampered Groth16 proof passes every cheap check and must still be rejected by the
    /// verifier — proving the verifier is actually consulted, not assumed.
    function test_CastVote_RevertsOnTamperedGroth16Proof() public {
        BallotBox.SemaphoreProof memory proof = _proof("proofA1");
        proof.points[0] = proof.points[0] + 1;

        vm.expectRevert(BallotBox.InvalidProof.selector);
        ballotBox.castVote(electionA, _ciphertext("ciphertext1"), _cpProof("chaumPedersenProof1"), proof);
    }

    /// Off-chain clients resolve the registry through the box rather than hard-coding an address.
    function test_Registry_ReturnsPinnedRegistry() public view {
        assertEq(address(ballotBox.registry()), address(registry));
    }
}
