/**
 * Shared ESLint flat config preset for all Keystone packages.
 * Consumed by each package's eslint.config.js via @keystone/config/eslint-preset.
 *
 * Typed-linting notes:
 * - `@typescript-eslint/no-floating-promises` needs type information. We use
 *   projectService (typescript-eslint v8), which locates each package's own
 *   tsconfig.json per file — no per-package parserOptions wiring needed.
 * - Files OUTSIDE any tsconfig still need type info for typed rules. They are
 *   handled by `allowDefaultProject` (loose default compiler options). Keep
 *   this list SMALL — anything real belongs in a package tsconfig.
 * - `tsconfigRootDir` is intentionally unset: it defaults to CWD, and turbo
 *   runs each package's lint script from that package's directory.
 * - JS files (eslint.config.js, next.config.js, postcss.config.js) get the
 *   non-typed rules only — the typed block is scoped to *.{ts,tsx}.
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Build outputs and caches. Without this, `eslint .` in a package also
    // walks dist/, which fails typed-linting on emitted .d.ts/.js files.
    // next-env.d.ts is regenerated by `next build` — never lint generated files.
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/out/**',
      '**/coverage/**',
      '**/.turbo/**',
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    ignores: [
      // Root-level *.config.ts (tailwind.config.ts, vite.config.ts) are exempt
      // from typed linting: some live inside a package tsconfig (Next apps),
      // some outside (crypto's vitest.config.ts) — projectService errors if a
      // file is in BOTH the project and allowDefaultProject. Non-typed rules
      // still apply to them below.
      '**/*.config.ts',
    ],
    languageOptions: {
      parserOptions: {
        // allowDefaultProject lives INSIDE the projectService options object —
        // as a sibling of `projectService: true` it would be silently ignored.
        projectService: {
          // NOTE: allowDefaultProject globs must NOT contain '**' (enforced by
          // typescript-eslint). Single-star only — test dirs must stay flat, or
          // the files belong in a real tsconfig instead.
          allowDefaultProject: ['test/*.ts', 'tests/*.ts'],
        },
      },
    },
  },
  {
    // Non-typed rules: safe for JS and TS alike (unused-vars, type-imports).
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Typed rules MUST stay scoped to TS files: they crash on JS files, which
    // never get the projectService parserOptions above.
    files: ['**/*.ts', '**/*.tsx'],
    ignores: ['**/*.config.ts'],
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
    },
  },
  {
    // Tooling config files (eslint.config.js, next.config.js, postcss.config.js)
    // are CommonJS: they use require/module, which js.recommended's ES-only
    // globals do not cover.
    files: ['**/*.config.js'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'writable',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
);
